name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true
    - run: cargo install cargo-leptos
    - name: Build
      run: cargo leptos build --release
    - name: Run tests
      run: cargo leptos test
